# -*- coding: utf-8 -*-
"""insurance_da (1).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cEbR8DEhGc9lrJKvo2to3hBwFekMpGnI
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

path='/content/insurance (1).csv'
df=pd.read_csv(path)
df

df.shape

df.count()

df.info()

df.describe()

sns.heatmap(df.corr(),annot=True)

df_small=df[['age','bmi','children','charges']]

sns.pairplot(df_small,hue='charges')

sns.lmplot(x="charges", y="age", hue="smoker", data=df);

"""High charges paid by smoker person """

sns.relplot(x="charges" , y="bmi",hue="charges", data=df)

"""Also all the high charges paid by only those people who have bmi above 30+"""

sns.relplot(x="charges" , y="age",hue="charges", data=df)

"""charges also increased when age increase"""

sns.lmplot(x="charges", y="bmi", hue="smoker", data=df);

"""Here we can see that high charges paid by people who have bmi above 30+ and a habit of smoking

Male smoker are high as compare to female,but most of people are non smoker
"""

sns.countplot(x='sex',data=df,hue="smoker")

"""Male people paid high charges as compare to female"""

sns.histplot(data=df, x="charges",hue="smoker", multiple="dodge")

"""non smoker person paid less charges, so it means smoking habit effacting charges of insuranse"""

plt.figure(figsize=(12,8))
sns.boxplot(df['sex'],df['charges'])
sns.swarmplot(x="sex",y="charges",data=df,color=".25")

sns.histplot(data=df, x="age",hue="smoker", multiple="dodge")

"""people around the age of 20 to 25 are high smoker person

CONCLUION : the charges are effecting by the bmi and smoker
"""